#!/usr/bin/env bash
file="/etc/passwd"

# Check if the file exists
if [ -e "$file" ]; then
    # Use IFS to set ':' as the field separator
    IFS=":"
    # Read each line of the file
    while read -r username _ uid _ _ home _
    do
        echo "Username: $username"
        echo "User ID: $uid"
        echo "Home directory: $home"
    done < "$file"
    # Reset IFS
    unset IFS
else
    echo "File $file does not exist"
fi
